//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_Hammadde
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> HammaddeGirisTarihi { get; set; }
        public string Tedarikci { get; set; }
        public string KatkiIsmi { get; set; }
        public string UrunKodu { get; set; }
        public string Fonksiyon { get; set; }
        public Nullable<double> Dozaj { get; set; }
        public decimal Miktar { get; set; }
        public string MiktarBirim { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string FiyatBirim { get; set; }
        public string Ozellik { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> HammaddeGelisMiktari { get; set; }
        public string KullanımDurumu { get; set; }
        public Nullable<decimal> İşletmeStok { get; set; }
    }
}
