//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_FikirHavuzuGuncelDurum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARGE_FikirHavuzuGuncelDurum()
        {
            this.ARGE_FikirHavuzu = new HashSet<ARGE_FikirHavuzu>();
        }
    
        public int ID { get; set; }
        public string FikirHavuzuGuncelDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_FikirHavuzu> ARGE_FikirHavuzu { get; set; }
    }
}
