//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_ProjeDenemeIplikDetay
    {
        public int ID { get; set; }
        public string IplikSecimi { get; set; }
        public string MamulTuru { get; set; }
        public string PartiNo { get; set; }
        public Nullable<int> Denye { get; set; }
        public Nullable<int> Flaman { get; set; }
        public string Aciklama { get; set; }
        public string Bilesen1 { get; set; }
        public string Bilesen2 { get; set; }
        public string Bilesen3 { get; set; }
        public string Bilesen4 { get; set; }
        public string Bilesen5 { get; set; }
        public Nullable<int> ProjeId { get; set; }
        public Nullable<int> DenemeId { get; set; }
    
        public virtual ARGE_Proje ARGE_Proje { get; set; }
        public virtual ARGE_ProjeDenemeleri ARGE_ProjeDenemeleri { get; set; }
    }
}
