//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARGE_Personel()
        {
            this.ARGE_PersonelDisaridaGecirilenSure = new HashSet<ARGE_PersonelDisaridaGecirilenSure>();
            this.ARGE_PersonelProje = new HashSet<ARGE_PersonelProje>();
            this.ARGE_Proje = new HashSet<ARGE_Proje>();
            this.ARGE_ProjeDisiCalisma = new HashSet<ARGE_ProjeDisiCalisma>();
        }
    
        public int PersonelId { get; set; }
        public string KullaniciAdi { get; set; }
        public string PersonelKodu { get; set; }
        public string AdSoyad { get; set; }
        public string Sifre { get; set; }
        public string Email { get; set; }
        public string Aciklama { get; set; }
        public string Email2 { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_PersonelDisaridaGecirilenSure> ARGE_PersonelDisaridaGecirilenSure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_PersonelProje> ARGE_PersonelProje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_Proje> ARGE_Proje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_ProjeDisiCalisma> ARGE_ProjeDisiCalisma { get; set; }
    }
}
