//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_Proje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARGE_Proje()
        {
            this.ARGE_DenemeIstek = new HashSet<ARGE_DenemeIstek>();
            this.ARGE_FikirHavuzu = new HashSet<ARGE_FikirHavuzu>();
            this.ARGE_Maliyet = new HashSet<ARGE_Maliyet>();
            this.ARGE_Numune = new HashSet<ARGE_Numune>();
            this.ARGE_PersonelDisaridaGecirilenSure = new HashSet<ARGE_PersonelDisaridaGecirilenSure>();
            this.ARGE_PersonelProje = new HashSet<ARGE_PersonelProje>();
            this.ARGE_ProjeDenemeleri = new HashSet<ARGE_ProjeDenemeleri>();
            this.ARGE_ProjeGuncelBilgi = new HashSet<ARGE_ProjeGuncelBilgi>();
            this.ARGE_Sarfiyat = new HashSet<ARGE_Sarfiyat>();
        }
    
        public int ID { get; set; }
        public string ProjeAdi { get; set; }
        public string ProjeKodu { get; set; }
        public string ProjeKisaAd { get; set; }
        public Nullable<System.DateTime> ProjeBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> ProjeBitisTarihi { get; set; }
        public bool ProjeDurum { get; set; }
        public decimal ToplamAdamAy { get; set; }
        public decimal MaliyetOngorusu { get; set; }
        public int ProjeYurutucusuId { get; set; }
        public string ProjeKonusu { get; set; }
        public string ProjedeYapilacaklar { get; set; }
        public string ProjeArgeYonu { get; set; }
        public string ProjeCiktilari { get; set; }
        public string ProjeDestekDurumu { get; set; }
        public int PersonelSayisi { get; set; }
        public string Aciklama { get; set; }
        public string ProjeKonusununIhtiyaclari { get; set; }
        public string HizmetAlimiKonusuYeri { get; set; }
        public string HizmetAlimiTutari { get; set; }
        public Nullable<decimal> OzkaynakTutari { get; set; }
        public Nullable<decimal> PersonelButcesi { get; set; }
        public Nullable<int> IsBirligiTuruId { get; set; }
        public string Aciklama2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_DenemeIstek> ARGE_DenemeIstek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_FikirHavuzu> ARGE_FikirHavuzu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_Maliyet> ARGE_Maliyet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_Numune> ARGE_Numune { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_PersonelDisaridaGecirilenSure> ARGE_PersonelDisaridaGecirilenSure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_PersonelProje> ARGE_PersonelProje { get; set; }
        public virtual ARGE_ProjeIsBirligiTuru ARGE_ProjeIsBirligiTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_ProjeDenemeleri> ARGE_ProjeDenemeleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_ProjeGuncelBilgi> ARGE_ProjeGuncelBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_Sarfiyat> ARGE_Sarfiyat { get; set; }
        public virtual ARGE_Personel ARGE_Personel { get; set; }
    }
}
