//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_Sarfiyat
    {
        public int SarfiyatId { get; set; }
        public Nullable<System.DateTime> SarfiyatTarih { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public string Birim { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> ProjeId { get; set; }
        public string SarfiyatCinsi { get; set; }
    
        public virtual ARGE_Proje ARGE_Proje { get; set; }
    }
}
