//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_DenemeChips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARGE_DenemeChips()
        {
            this.ARGE_DenemeIstek = new HashSet<ARGE_DenemeIstek>();
            this.ARGE_ProjeDenemeleri = new HashSet<ARGE_ProjeDenemeleri>();
        }
    
        public int ID { get; set; }
        public string ChipsAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_DenemeIstek> ARGE_DenemeIstek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARGE_ProjeDenemeleri> ARGE_ProjeDenemeleri { get; set; }
    }
}
