//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_Makineler
    {
        public int ID { get; set; }
        public string MakineNo { get; set; }
        public string MakineAdi { get; set; }
        public string MakineTuru { get; set; }
        public string MakineGrubu { get; set; }
        public string MakineTipi { get; set; }
        public string MakineBolum { get; set; }
    }
}
