//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_ProjeDenemeleri
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DenemeTarih { get; set; }
        public Nullable<int> ProjeId { get; set; }
        public string DenemeAdi { get; set; }
        public string POYLotu { get; set; }
        public string POYDtex { get; set; }
        public string Katki { get; set; }
        public string POYMakinesi { get; set; }
        public string POYMiktari { get; set; }
        public string TekstureLotu { get; set; }
        public string TekstureDtex { get; set; }
        public string TekstureMakinesi { get; set; }
        public string TekstureMiktari { get; set; }
        public string BukumLotu { get; set; }
        public string BukumDtex { get; set; }
        public string BukumMakinesi { get; set; }
        public string BukumMiktari { get; set; }
        public string HavaTekstureLotu { get; set; }
        public string HavaTekstureDtex { get; set; }
        public string HavaTekstureMiktari { get; set; }
        public string Aciklama { get; set; }
        public string Bilesen1 { get; set; }
        public string POYLotu2 { get; set; }
        public string POYLotu3 { get; set; }
        public string POYLotu4 { get; set; }
        public string POYLotu5 { get; set; }
        public string POYLotu6 { get; set; }
        public string POYLotu7 { get; set; }
        public string POYLotu8 { get; set; }
        public string POYLotu9 { get; set; }
        public string POYLotu10 { get; set; }
        public string DisMakine { get; set; }
        public string Chips2 { get; set; }
        public string HavaTekstureMakinesi { get; set; }
        public Nullable<int> Chips { get; set; }
        public Nullable<System.DateTime> TekstureDenemeTarihi { get; set; }
        public Nullable<System.DateTime> BukumDenemeTarihi { get; set; }
        public Nullable<System.DateTime> HavaTekstureDenemeTarihi { get; set; }
        public Nullable<int> POYDenemeKesitId { get; set; }
        public Nullable<int> TekstureDenemeKesitId { get; set; }
        public Nullable<int> BukumDenemeKesitId { get; set; }
        public Nullable<int> HavaTekstureDenemeKesitId { get; set; }
        public string POYDenemeKesit { get; set; }
        public string TekstureDenemeKesit { get; set; }
        public string BukumDenemeKesit { get; set; }
        public string HavaTekstureDenemeKesit { get; set; }
    
        public virtual ARGE_DenemeChips ARGE_DenemeChips { get; set; }
        public virtual ARGE_KesitTipi ARGE_KesitTipi { get; set; }
        public virtual ARGE_KesitTipi ARGE_KesitTipi1 { get; set; }
        public virtual ARGE_KesitTipi ARGE_KesitTipi2 { get; set; }
        public virtual ARGE_KesitTipi ARGE_KesitTipi3 { get; set; }
        public virtual ARGE_Proje ARGE_Proje { get; set; }
    }
}
