//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_DenemeIstek
    {
        public int DenemeIstekId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Katki { get; set; }
        public string KesitTipi { get; set; }
        public string Chips { get; set; }
        public string Dozaj { get; set; }
        public string POYDtex { get; set; }
        public string POYReferans { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> ProjeDenemeIstekId { get; set; }
        public string POYMiktari { get; set; }
        public Nullable<int> KesitTipiId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<int> KesitTipiId2 { get; set; }
        public Nullable<int> KesitTipiId3 { get; set; }
        public Nullable<int> ChipsSecme { get; set; }
    
        public virtual ARGE_DenemeChips ARGE_DenemeChips { get; set; }
        public virtual ARGE_DenemeDurum ARGE_DenemeDurum { get; set; }
        public virtual ARGE_Proje ARGE_Proje { get; set; }
        public virtual ARGE_KesitTipi ARGE_KesitTipi { get; set; }
        public virtual ARGE_KesitTipi ARGE_KesitTipi1 { get; set; }
        public virtual ARGE_KesitTipi ARGE_KesitTipi2 { get; set; }
    }
}
