//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_PersonelDisaridaGecirilenSure
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CikisTarih { get; set; }
        public string DisGorevAdi { get; set; }
        public string Yer { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> ProjeId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public string CikisSaati { get; set; }
        public string GirisSaati { get; set; }
    
        public virtual ARGE_Proje ARGE_Proje { get; set; }
        public virtual ARGE_Personel ARGE_Personel { get; set; }
    }
}
