//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_ProjeDisiCalisma
    {
        public int ID { get; set; }
        public string ProjeKonusu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Guncelleme { get; set; }
        public string Numuneler { get; set; }
        public Nullable<int> ProjeSorumluId { get; set; }
    
        public virtual ARGE_Personel ARGE_Personel { get; set; }
    }
}
