//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGE_Numune
    {
        public int ID { get; set; }
        public string MusteriFirma { get; set; }
        public string IlgiliKisi { get; set; }
        public string Iletisim { get; set; }
        public Nullable<int> PartiId { get; set; }
        public string Miktar { get; set; }
        public Nullable<System.DateTime> HatirlatmaTarihi { get; set; }
        public string PartiKodu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> ProjeId { get; set; }
        public string NumuneAdi { get; set; }
    
        public virtual ARGE_Proje ARGE_Proje { get; set; }
    }
}
