//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaliyetRaporView
    {
        public int MaliyetId { get; set; }
        public string ProjeKodu { get; set; }
        public string Personel { get; set; }
        public string MaliyetAdi { get; set; }
        public Nullable<System.DateTime> MaliyetTarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> KDVliMiktar { get; set; }
        public Nullable<decimal> KDVsizMiktar { get; set; }
    }
}
