//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POLYTEKS_ARGE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTKS_ARGE1 : DbContext
    {
        public PTKS_ARGE1()
            : base("name=PTKS_ARGE1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARGE_DenemeChips> ARGE_DenemeChips { get; set; }
        public virtual DbSet<ARGE_DenemeDurum> ARGE_DenemeDurum { get; set; }
        public virtual DbSet<ARGE_DenemeIstek> ARGE_DenemeIstek { get; set; }
        public virtual DbSet<ARGE_FikirHavuzu> ARGE_FikirHavuzu { get; set; }
        public virtual DbSet<ARGE_FikirHavuzuGuncelDurum> ARGE_FikirHavuzuGuncelDurum { get; set; }
        public virtual DbSet<ARGE_FikirHavuzuOnayDurum> ARGE_FikirHavuzuOnayDurum { get; set; }
        public virtual DbSet<ARGE_Hammadde> ARGE_Hammadde { get; set; }
        public virtual DbSet<ARGE_KesitTipi> ARGE_KesitTipi { get; set; }
        public virtual DbSet<ARGE_Makineler> ARGE_Makineler { get; set; }
        public virtual DbSet<ARGE_Maliyet> ARGE_Maliyet { get; set; }
        public virtual DbSet<ARGE_Numune> ARGE_Numune { get; set; }
        public virtual DbSet<ARGE_PersonelDisaridaGecirilenSure> ARGE_PersonelDisaridaGecirilenSure { get; set; }
        public virtual DbSet<ARGE_PersonelProje> ARGE_PersonelProje { get; set; }
        public virtual DbSet<ARGE_Proje> ARGE_Proje { get; set; }
        public virtual DbSet<ARGE_ProjeDenemeleri> ARGE_ProjeDenemeleri { get; set; }
        public virtual DbSet<ARGE_ProjeDisiCalisma> ARGE_ProjeDisiCalisma { get; set; }
        public virtual DbSet<ARGE_ProjeGuncelBilgi> ARGE_ProjeGuncelBilgi { get; set; }
        public virtual DbSet<ARGE_ProjeIsBirligiTuru> ARGE_ProjeIsBirligiTuru { get; set; }
        public virtual DbSet<ARGE_Sarfiyat> ARGE_Sarfiyat { get; set; }
        public virtual DbSet<ARGE_Personel> ARGE_Personel { get; set; }
    }
}
